version: '3'
services:
  service-catalog:
    build:
      context: service-catalog
    ports:
      - "8082:8082"
    volumes:
      - ./service-catalog/db:/data
      - ./service-catalog/conf:/conf

  resource-catalog:
    build:
      context: resource-catalog
    ports:
      - "8081:8081"
    links:
      - service-catalog
    volumes:
      - ./resource-catalog/db:/data
      - ./resource-catalog/conf:/conf

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "8883:8883"     

  device-gateway:
    build:
      context: device-gateway
    ports:
      - "8080:8080"
    links:
      - service-catalog
      - resource-catalog
    volumes:
      - ./device-gateway/conf:/conf